# Generated by Django 3.1.1 on 2020-10-31 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dadwebsite', '0002_auto_20201031_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='data_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 13, 16, 19, 857124, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='users',
            name='message',
            field=models.CharField(max_length=200),
        ),
    ]
